micronaut:
  application:
    name: demo

datasources:
  default:
    url: jdbc:postgresql://host.docker.internal:5432/demo
    username: postgres
    password: paula@123
    driverClassName: org.postgresql.Driver

---
jpa:
  default:
    packages-to-scan:
      - 'com.deviot.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true

